version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmsvd-dashboard
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
